Init

diff --git a/.github/workflows/send_notification_auto.yml b/.github/workflows/send_notification_auto.yml
--- a/.github/workflows/send_notification_auto.yml
+++ b/.github/workflows/send_notification_auto.yml
@@ -1,8 +1,6 @@
 name: Send Slack Notification
 on:
-  create:
-    branches:
-      - '*'
+  push:
   workflow_dispatch:
 
 jobs:
@@ -12,6 +10,7 @@ jobs:
     #Important
     outputs:
       status: ${{ job.status }}
+      message: ${{ steps.status_update1.outputs.message }}
 
     steps:
       - name: Extract branch name
@@ -33,7 +32,8 @@ jobs:
       - name: Exit Status Update1
         id: status_update1
         run: |
-          exit 0
+          echo "message={emoji} *{workflow}* {status_message} in THE MONOREPO HAHAHA <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}> *<{run_url}|View Run>* " >> $GITHUB_OUTPUT
+          exit 1
 
   second_job:
     name: second-job
@@ -50,24 +50,53 @@ jobs:
 
   #Important
   slack_setup:
+    strategy:
+      matrix:
+        needss: [check_branch-name, second_job]
     runs-on: ubuntu-latest
-    needs: [check_branch-name, second_job]
+    #important
+    #Uses stategy matrix to only have one depenndancy at a time
+    needs: "${{ matrix.needss }}"
     if: always()
     outputs:
       status: ${{steps.set_status.outputs.status}}
+      slack_id: ${{steps.get_github_bio.outputs.bio}}
+      message: ${{steps.set_message.outputs.message}}
     steps:
       - name: Set status
         id: set_status
         shell: bash
-        #Réfléchir à comment intégrer les autres status: skipped, warning, cancelled
+        #If there's at least one "failure" job, the overall status is "failure."
+        #If all jobs are "success" or "skipped," the overall status is "success."
+        #If there's at least one "cancelled" job, the overall status is "cancelled."
+        #If there's at least one "warning" job and no "failure" jobs, the overall status is "warning."
         run: |
-          if ${{ contains(needs.*.outputs.status, 'failure') }}; then 
+          if ${{ contains(needs.*.outputs.status, 'failure') }}; then
             echo "status=failure" >> $GITHUB_OUTPUT
+          elif ${{ contains(needs.*.outputs.status, 'cancelled') }}; then
+            echo "status=cancelled" >> $GITHUB_OUTPUT
+          elif ${{ contains(needs.*.outputs.status, 'warning') }}; then
+            echo "status=warning" >> $GITHUB_OUTPUT
           else
             echo "status=success" >> $GITHUB_OUTPUT
           fi
-      #- name: Get Slack ID
-      #  run: |
+      - name: Set message
+        id: set_message
+        shell: bash
+        run: |
+          if ${{ needs.*.outputs.message }} = '[]'; then
+            echo "message="{emoji} *{workflow}* {status_message} in HOHOHOHO <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}> *<{run_url}|View Run>* "
+      - run: sudo apt-get install jq -y
+      - name: Get GitHub Bio
+        id: get_github_bio
+        run: |
+          id_git=$(curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ github.token }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/users/${{ github.actor }} \
+          | jq -r '.bio'); \
+          echo "bio=$id_git" >> $GITHUB_OUTPUT
 
   #Important
   slack_notification:
@@ -76,8 +105,11 @@ jobs:
     uses: UlysseCarpentier/GHActions-Git-Brother/.github/workflows/slack_notification.yml@main
     with:
       status: "${{ needs.slack_setup.outputs.status }}"
-      message_format: ""
+      message_format: "${{ needs.slack_setup.outputs.message }}"
+      mention_users: "${{ needs.slack_setup.outputs.slack_id }}"
+    #Changer le webhook url pour aller cherche le secret
     secrets: inherit
+
 
 
 
